Repository JoeKarow/netwerkr, pull requests merged in 2022-06, with the labels that each got.

#22 feat: implement NextAuth & initial mongoDB connection
  .gitignore
  apps/web/.env.example
  apps/web/package.json
  apps/web/pages/_app.js
  apps/web/pages/api/auth/[...nextauth].js
  apps/web/pages/index.jsx
  packages/lib/.eslintrc.js
  packages/lib/index.js
  packages/lib/mongodb.js
  packages/lib/package.json
  packages/netwerkr-config/package.json
  packages/ui/components/AuthSessionStatus.jsx
  packages/ui/components/index.js
  packages/ui/package.json
  pnpm-lock.yaml
  turbo.json
Labels: new-feature, priority-high

#23 docs(global): 📝 Fix license badge
  README.md
Labels: bugfix

#25 chore(global): 🔨 change linting config
  .husky/pre-commit
  packages/lib/mongodb.js
  packages/lib/package.json
  packages/lib/tsconfig.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: maintenance

#30 Set up testing
  .eslintrc.js
  apps/docs/package.json
  apps/web/__tests__/index.test.jsx
  apps/web/jest.config.js
  apps/web/jest.setup.js
  apps/web/package.json
  jest.config.js
  package.json
  packages/eslint-config-netwerkr/package.json
  packages/ui/__test__/testing.test.js
  packages/ui/jest.config.js
  packages/ui/jest.config.js.next
  packages/ui/jest.setup.js
  packages/ui/nextui.d.ts
  packages/ui/nextui.js
  packages/ui/package.json
  pnpm-lock.yaml
  turbo.json
Labels: maintenance

#32 feat/login-popover
  .eslintrc.js
  .vscode/launch.json
  apps/docs/package.json
  apps/web/.vscode/launch.json
  apps/web/babel.config.js
  apps/web/package.json
  apps/web/pages/_app.jsx
  apps/web/pages/api/auth/[...nextauth].js
  package.json
  packages/eslint-config-netwerkr/package.json
  packages/netwerkr-config/package.json
  packages/ui/components/LoginProvider.jsx
  packages/ui/components/index.js
  packages/ui/package.json
  packages/ui/section/HeaderAction.jsx
  pnpm-lock.yaml
Labels: new-feature, priority-medium, in-progress

#38 Update develop to be up to date with main
  .github/workflows/dependency-review.yml
  .github/workflows/issues-from-TODO-comments.yml
  .husky/post-checkout
  .husky/post-commit
  .husky/post-merge
  .husky/pre-commit
  .husky/pre-push
  .vscode/launch.json
  README.md
  apps/docs/package.json
  apps/web/.gitignore
  apps/web/.vscode/launch.json
  apps/web/__tests__/index.test.jsx
  apps/web/babel.config.js
  apps/web/data/navLinks.js
  apps/web/jest.config.js
  apps/web/jest.setup.js
  apps/web/package.json
  apps/web/pages/_app.js
  apps/web/pages/_app.jsx
  apps/web/pages/_document.js
  apps/web/pages/_document.jsx
  apps/web/pages/api/auth/[...nextauth].js
  apps/web/pages/api/navigation.js
  apps/web/pages/index.jsx
  apps/web/prisma/schema.prisma
  jest.config.js
  package.json
  packages/eslint-config-netwerkr/package.json
  packages/lib/mongodb.js
  packages/lib/package.json
  packages/lib/tsconfig.json
  packages/netwerkr-config/package.json
  packages/ui/__test__/testing.test.js
  packages/ui/components/LoginProvider.jsx
  packages/ui/components/index.js
  packages/ui/jest.config.js
  packages/ui/jest.config.js.next
  packages/ui/jest.setup.js
  packages/ui/layout/navLinks.js
  packages/ui/layout/web.jsx
  packages/ui/nextui.d.ts
  packages/ui/nextui.js
  packages/ui/package.json
  packages/ui/section/HeaderAction.jsx
  pnpm-lock.yaml
  stackhawk.yml
  turbo.json
Labels: maintenance

#40 User Dash
  pnpm-lock.yaml
Labels: new-feature

#44 chore(global): :hammer: bump deps
  packages/eslint-config-netwerkr/package.json
  pnpm-lock.yaml
  renovate.json
Labels: dependencies

#74 chore(deps): bump deps
  .github/workflows/release.yml
  apps/web/package.json
  package.json
  packages/eslint-config-netwerkr/package.json
  packages/lib/package.json
  packages/netwerkr-config/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: dependencies, maintenance, automerge

#75 feat(ui): :sparkles: storybook
  apps/web/babel.config.js.disable
  apps/web/package.json
  apps/web/pages/_app.tsx
  apps/web/pages/_document.tsx
  apps/web/pages/api/auth/[...nextauth].ts
  apps/web/types/next-auth.d.ts
  package.json
  packages/ui/.eslintrc.js
  packages/ui/.storybook/main.js
  packages/ui/.storybook/preview.tsx
  packages/ui/components/UserButton.tsx
  packages/ui/hooks/index.ts
  packages/ui/hooks/useProviders.js
  packages/ui/hooks/useProviders.ts
  packages/ui/mockdata/contactTable.ts
  packages/ui/mockdata/featuresGrid.ts
  packages/ui/mockdata/index.ts
  packages/ui/mockdata/navbarNested.ts
  packages/ui/mockdata/user.ts
  packages/ui/next.config.js
  packages/ui/package.json
  packages/ui/section/FeaturesGrid.stories.tsx
  packages/ui/section/FeaturesGrid.tsx
  packages/ui/section/NavbarNested.tsx
  packages/ui/stories/Button.stories.tsx
  packages/ui/stories/Button.tsx
  packages/ui/stories/Header.stories.tsx
  packages/ui/stories/Header.tsx
  packages/ui/stories/Introduction.stories.mdx
  packages/ui/stories/Page.stories.tsx
  packages/ui/stories/Page.tsx
  packages/ui/stories/assets/code-brackets.svg
  packages/ui/stories/assets/colors.svg
  packages/ui/stories/assets/comments.svg
  packages/ui/stories/assets/direction.svg
  packages/ui/stories/assets/flow.svg
  packages/ui/stories/assets/plugin.svg
  packages/ui/stories/assets/repo.svg
  packages/ui/stories/assets/stackalt.svg
  packages/ui/stories/button.css
  packages/ui/stories/header.css
  packages/ui/stories/page.css
  packages/ui/style/theme.ts
  packages/ui/tsconfig.json
  packages/ui/types/next-auth.d.ts
  pnpm-lock.yaml
  turbo.json
Labels: new-feature, dependencies, automerge

#76 chore(global): :hammer: remove dup eslint-next, add deadpendency conf
  .github/deadpendency.yaml
  package.json
  packages/netwerkr-config/package.json
  pnpm-lock.yaml
Labels: dependencies, maintenance, automerge

#77 feat(web): :sparkles: trpc prisma generator
  .gitignore
  .husky/pre-commit
  apps/web/package.json
  apps/web/prisma/schema.prisma
  apps/web/prisma/zod/index.ts
  package.json
  pnpm-lock.yaml
Labels: new-feature, automerge

#78 Merge develop to main
  .github/deadpendency.yaml
  .gitignore
  .husky/pre-commit
  apps/web/babel.config.js.disable
  apps/web/package.json
  apps/web/pages/_app.tsx
  apps/web/pages/_document.tsx
  apps/web/pages/api/auth/[...nextauth].ts
  apps/web/prisma/schema.prisma
  apps/web/prisma/zod/index.ts
  apps/web/types/next-auth.d.ts
  package.json
  packages/netwerkr-config/package.json
  packages/ui/.eslintrc.js
  packages/ui/.storybook/main.js
  packages/ui/.storybook/preview.tsx
  packages/ui/components/UserButton.tsx
  packages/ui/hooks/index.ts
  packages/ui/hooks/useProviders.js
  packages/ui/hooks/useProviders.ts
  packages/ui/mockdata/contactTable.ts
  packages/ui/mockdata/featuresGrid.ts
  packages/ui/mockdata/index.ts
  packages/ui/mockdata/navbarNested.ts
  packages/ui/mockdata/user.ts
  packages/ui/next.config.js
  packages/ui/package.json
  packages/ui/section/FeaturesGrid.stories.tsx
  packages/ui/section/FeaturesGrid.tsx
  packages/ui/section/NavbarNested.tsx
  packages/ui/stories/Button.stories.tsx
  packages/ui/stories/Button.tsx
  packages/ui/stories/Header.stories.tsx
  packages/ui/stories/Header.tsx
  packages/ui/stories/Introduction.stories.mdx
  packages/ui/stories/Page.stories.tsx
  packages/ui/stories/Page.tsx
  packages/ui/stories/assets/code-brackets.svg
  packages/ui/stories/assets/colors.svg
  packages/ui/stories/assets/comments.svg
  packages/ui/stories/assets/direction.svg
  packages/ui/stories/assets/flow.svg
  packages/ui/stories/assets/plugin.svg
  packages/ui/stories/assets/repo.svg
  packages/ui/stories/assets/stackalt.svg
  packages/ui/stories/button.css
  packages/ui/stories/header.css
  packages/ui/stories/page.css
  packages/ui/style/theme.ts
  packages/ui/tsconfig.json
  packages/ui/types/next-auth.d.ts
  pnpm-lock.yaml
  turbo.json
Labels: new-feature, automerge
